### ISSUE TITLE
"ANDROID_SDK_ROOT" not found, build fails

### ISSUE THREAD

**Issue by mario-neb** [hey24sheep/azure-flutter-tasks#12]
![flutter_build_error](https://user-images.githubusercontent.com/50882870/135101445-2ba4364d-a28d-4d57-bf91-cb6ac3dd17b0.PNG)

The pipeline fails on flutter build command 

![sc_pipeline](https://user-images.githubusercontent.com/50882870/135101779-98d441a5-9d58-42db-9069-c8b6023061a5.PNG)

**Comment by hey24sheep** [comment]
Can you show me the generated build command here? 


The build fail is because you don't have `ANDROID_SDK_ROOT` var setup. Have a look [here](https://stackoverflow.com/questions/50403643/how-to-find-the-location-of-the-android-sdk-on-a-hosted-agent-in-visual-studio-t). It is done by Azure itself and not by the tasks.

**Comment by mario-neb** [comment]
Understood, thanks for the reply. Do you know if its possible if I can build also ios inside an agent hosted on windows servers?

**Comment by hey24sheep** [comment]
Unfortunately, no. Apple doesn't allow IOS builds on any other platform or hardware. They are very strict regarding this, I personally find it annyoing and troublesome but hey, it's Apple :D 

If this solves your problem, let me know by closing this issue.
