### ISSUE TITLE
iOS build IPA failed

### ISSUE THREAD

**Issue by coccyx-cyst** [hey24sheep/azure-flutter-tasks#35]
Getting  error: exportArchive: "Runner.app" requires a provisioning profile with the Push Notifications feature.

If I am building non-ipa option there's no error.

I am pre-installing cert and profile 
![image](https://user-images.githubusercontent.com/72284940/156131402-2872032f-6851-4508-b639-9c99a7c1c297.png)

my ExportOptions.plist contains:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
     <key>compileBitcode</key>
     <true/>
     <key>method</key>
     <string>app-store</string>
     <key>signingStyle</key>
     <string>automatic</string>
     <key>stripSwiftSymbols</key>
     <true/>
     <key>teamID</key>
     <string>MyTeamID</string>
     <key>thinning</key>
     <string>&lt;none&gt;</string>
</dict>
</plist>
```

Setting path to ExportOptions.plist like this:
![image](https://user-images.githubusercontent.com/72284940/156131725-3fc6512e-c774-4afa-b927-199fdd4ed73b.png)

Could you tell me what I am doing wrong? @hey24sheep 

Btw, of course my profile contains push-notification feature

**Comment by hey24sheep** [comment]
Hi, we use ios build in our organization so I am not very educated about `build ipa` option. I think you have not added provisional profile key in your export options and it is not being able to find it.

Have a look [here](https://stackoverflow.com/questions/67386631/flutter-ios-signing-issue-runner-requires-a-provisioning-profile-with-the-pu). Check this [issue ](https://stackoverflow.com/questions/45748140/xcode-9-distribution-build-fails-because-format-of-exportoptions-plist-has-chang)as well.

If the link doesn't help try this
- Check if `build ipa` works locally on your system with the same profile.
- Second, you could try creating a new profile and see if it builds with that.

The problem is that it isn't able to find the related profile.

**Comment by coccyx-cyst** [comment]
@hey24sheep Ye, i've changed signingStyle to manual and added provisional profile key lately, so there's no issue. Tnx for reply.

**Comment by hey24sheep** [comment]
I am glad, it is solved 👍🏼

**Comment by jtmuller5** [comment]
@coccyx-cyst Would you be able to post your final exportOptions.plist? I'm attempting to do the same thing as you and for some reason I'm getting the error:

Error (Xcode): No profiles for 'com.example.my-app' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.my-app'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.

**Comment by coccyx-cyst** [comment]
@jtmuller5 
I got these options:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
     <key>compileBitcode</key>
     <true/>
     <key>method</key>
     <string>app-store</string>
    <key>provisioningProfiles</key>
    <dict>
        <key>$(packageName)</key>
        <string>$(profileName)</string>
    </dict>
      <key>signingCertificate</key>
      <string>Apple Distribution</string>
     <key>signingStyle</key>
     <string>manual</string>
     <key>stripSwiftSymbols</key>
     <true/>
     <key>teamID</key>
     <string>$(teamId)</string>
     <key>thinning</key>
     <string>&lt;none&gt;</string>
</dict>
</plist>
```

**Comment by MiroLiebschner** [comment]
@jtmuller5 Have you been able to resolve the problem? I am stuck with the same error message you posted.
