### ISSUE TITLE
flutter build ios take more than 1 hour to complete

### ISSUE THREAD

**Issue by AhmedKhattab95** [hey24sheep/azure-flutter-tasks#59]
I am running on flutter 3.3.7 and ios build task take time more than 47 minutes which is not acceptable at all if there is  a new updates should be done please inform us
![image](https://user-images.githubusercontent.com/17656876/201533604-06a6ea59-440b-420b-8e35-e7063fa7702d.png)

**Comment by hey24sheep** [comment]
@AhmedKhattab95 Build lengths are dependent on your project length. How complex and big your project is. Also, it is dependent on what kind of VM is running, if the build agent is local or hosted, etc.

If you think the build time is longer on latest Flutter. You can open an issue on Flutter's [Github](https://github.com/flutter/flutter).  This extension is just bridging the gap of calling build commands and has nothing to do with build time, how the app is built or the output of the build. 

I am closing this issue as this issue is not related to this extension.. Feel free to create this issue on Flutter's git.
