### ISSUE TITLE
Flutter install issue

### ISSUE THREAD

**Issue by samuel-jeyaraj** [hey24sheep/azure-flutter-tasks#70]
On using Flutter Install in Azure Devops server 2019 CI/CD pipeline, i am getting the following error when i choose Flutter custom version 3.3.9. When i use latest version i am not receiving this error.  Unfortunately i need this specific version. Can someone guide me in solving this error. 

```
##[section]Starting: Flutter Install
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.3.5
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io)
==============================================================================
Downloading: https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.3.9-stable.zip
Extracting archive
[command]C:\Windows\system32\chcp.com 65001
Active code page: 65001
[command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\DevOpsBuildAgent\_work\_temp\d1ad7440-a550-4801-aba6-0cc51ef1cf60', 'C:\DevOpsBuildAgent\_work\_temp\7339e4f1-5825-4cfb-ba35-a31a3ee62ce1')"
Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find a part of the path 'C:\DevOpsBuildAgent\_w
ork\_temp\7339e4f1-5825-4cfb-ba35-a31a3ee62ce1\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecy
cle-2.0.6\example\android\app\src\androidTest\java\io\flutter\plugins\flutter_plugin_android_lifecycle\MainActivityTest
.java'."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\D ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : DirectoryNotFoundException
 
##[error]Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
##[section]Finishing: Flutter Install
```

**Comment by hey24sheep** [comment]
Are you running this on Local Agent or Hosted Agent? 

It's showing you the error `"C:\DevOpsBuildAgent\", Directory not found`. If you are running local agent, check your directories. If it's hosted agent, then try running default Install first, see if that works or not.

**Comment by hey24sheep** [comment]
Hi, is this issue fixed. It will get closed soon as stale-inactive.

**Comment by nick-gallimore** [comment]
I just encountered this issue as well, using hosted Azure DevOps with a local agent, Flutter Install Task version 0.3.6 trying to install Flutter 3.3.10.

The problem is that older versions of Flutter appear to have a `.pub-cache` folder containing a cache of packages (I assume... I'm not a Flutter dev, just trying to get some Flutter code building for someone else). The problem is that the path of the file mentioned exceeds 260 characters when it's extracted into the agent's `Temp` directory, in my case the total path length is 263 characters. This causes the call to `[System.IO.Compression.ZipFile]::ExtractToDirectory` to fail with the above error. The really frustrating thing is that it appears to just be an example project that's included in this particular package, so not likely something we'd even need when doing a build, even if we happen to be using that package.

Newer versions have a `.pub-preload-cache` folder that is similar, but all the packages are zipped up so it's not a problem.

Strangely if I look in the tool cache for a newer version of Flutter that successfully installed (e.g., 3.10.1), the `.pub-preload-cache` folder doesn't exist, but I can't see that it's skipped when caching the tool. Not sure how to explain that one.

Let me know if you need more info / want logs / etc.

**Comment by hey24sheep** [comment]
@nick-gallimore Wow, that's really interesting. Thanks for the insight into this issue, really appreciate it.

I think that is an issue from Flutter's side. You can open this issue on their repository and tag this issue there. I will close it here as it is not related to this extension directly and it has been stale since Feb 28th 2023.
