### ISSUE TITLE
xcode_backend.sh

### ISSUE THREAD

**Issue by coleary01** [hey24sheep/azure-flutter-tasks#77]
Getting the below error message when using this extension on Azure Pipelines if anybody has any idea.

```
/bin/sh: /Users/runner/fvm/versions/stable/packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
    Command PhaseScriptExecution failed with a nonzero exit code
```

This is the contents of my Generated.xcconfig

```
// This is a generated file; do not edit or check into version control.
FLUTTER_ROOT=/Users/runner/hostedtoolcache/Flutter/3.3.9/macos/flutter
FLUTTER_APPLICATION_PATH=/Users/runner/work/1/mobile_ui
COCOAPODS_PARALLEL_CODE_SIGN=true
FLUTTER_TARGET=lib/main.dart
FLUTTER_BUILD_DIR=build
FLUTTER_BUILD_NAME=2022.2.1
FLUTTER_BUILD_NUMBER=81
EXCLUDED_ARCHS[sdk=iphonesimulator*]=i386 arm64
EXCLUDED_ARCHS[sdk=iphoneos*]=armv7
DART_OBFUSCATION=false
TRACK_WIDGET_CREATION=true
TREE_SHAKE_ICONS=false
PACKAGE_CONFIG=.dart_tool/package_config.json
```

I have even added the below script to the pipeline to create the directory for Flutter FVM.

`
mkdir -p $HOME/fvm/versions/stable
cp -a $(FlutterToolPath)/. $HOME/fvm/versions/stable/
`

**Comment by hey24sheep** [comment]
Hi, the issue is related to XCode and how it's configured and not with this extension.

Please read the links, (if these links don't help then Google search or Flutter's Github might)

- [StackOverflow issue](https://stackoverflow.com/questions/56844012/xcode-backend-sh-no-such-file-or-directory-do-i-need-to-create-this-file).
- [Flutter's issue](https://github.com/flutter/flutter/issues/56085)
