### ISSUE TITLE
Getting No profile found on Xcode build task/ Flutter task

### ISSUE THREAD

**Issue by AkshiptaMarico** [hey24sheep/azure-flutter-tasks#85]
Error_Msg while Xcode build 

    error: No profiles for 'com.xxxx.xxx' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.xxxx.xxx'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Runner' from project 'Runner')
    /Users/runner/work/1/s/claimautomation/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'flutter_local_notifications' from project 'Pods')
    /Users/runner/work/1/s/claimautomation/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'FMDB' from project 'Pods')
    /Users/runner/work/1/s/claimautomation/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'device_information' from project 'Pods')
    /Users/runner/work/1/s/claimautomation/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'Toast' from project 'Pods')

    Result bundle written to path:
    	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/flutter_tools.r7jTid/flutter_ios_build_temp_dirsU3tQ5/temporary_xcresult_bundle

Error (Xcode): No profiles for 'com.xxxx.xxx' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.xxxx.xxx'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.

It appears that there was a problem signing your application prior to installation on the device.

Verify that the Bundle Identifier in your project is your signing id in Xcode
  open ios/Runner.xcworkspace

Also try selecting 'Product > Build' to fix the problem.
Encountered error while archiving for device.

**Comment by AkshiptaMarico** [comment]
Even if we install provisioning profile installation task/ plugin

**Comment by hey24sheep** [comment]
Hi, this issue has been asked and closed multiple times here.

Sometimes the issue gets fixed when you delete old profiles and create new ones then you have bind them in XCode and build once locally. You can try doing that.

Unfortunately there is no single solution to this issue. So, I can't help you much here. The issue is from your XCode configuration and setup. 

Only Google search or StackOverflow can fix the problem. 

Go through these links where we have addressed this 

- [all related issues](https://github.com/hey24sheep/azure-flutter-tasks/issues?q=is%3Aissue+is%3Aclosed+ios+profile+)
- [issue#37](https://github.com/hey24sheep/azure-flutter-tasks/issues/37)
- [setup wiki](https://github.com/hey24sheep/azure-flutter-tasks/wiki/IOS-&-Android-Example-Setup-Guide)
- [IOS Setup](https://github.com/hey24sheep/azure-flutter-tasks/wiki/Our-IOS-Build-Solution)

This below one is the same issue and have fixed solution.
- [issue#49](https://github.com/hey24sheep/azure-flutter-tasks/issues/49) for same issue and fixed solutions. I hope it helps.

I hope this fixes your problem. I am closing this issue as it's not related to this extension and has been asked and solved here multiple times. Feel free to ask ask on old issues (in case you can't fix the problem).
